// Sample data for the teaching payment system
const sampleData = {
  // Vai trò trong hệ thống
  roles: [
    {
      id: 1,
      name: "Admin",
      displayName: "Quản trị viên",
      description: "Toàn quyền quản lý hệ thống",
      permissions: ["*"], // Tất cả quyền
    },
    {
      id: 2,
      name: "Dean",
      displayName: "Trưởng khoa",
      description: "Quản lý khoa và giáo viên trong khoa",
      permissions: [
        "view_department_teachers",
        "manage_department_classes",
        "view_department_reports",
        "assign_teachers",
        "view_department_salary",
      ],
    },
    {
      id: 3,
      name: "ViceDean",
      displayName: "Phó trưởng khoa",
      description: "Hỗ trợ quản lý khoa",
      permissions: [
        "view_department_teachers",
        "view_department_classes",
        "view_department_reports",
      ],
    },
    {
      id: 4,
      name: "Teacher",
      displayName: "Giáo viên",
      description: "Xem thông tin cá nhân và lịch dạy",
      permissions: [
        "view_own_schedule",
        "view_own_salary",
        "view_own_classes",
        "update_own_profile",
      ],
    },
  ],

  // Tài khoản người dùng
  users: [
    {
      id: 1,
      username: "admin",
      password: "admin123",
      roleId: 1,
      teacherId: null,
      departmentId: null,
      isActive: true,
      lastLogin: null,
      createdDate: "2024-01-01",
    },
    // Trưởng khoa
    {
      id: 2,
      username: "dean_cntt",
      password: "dean123",
      roleId: 2,
      teacherId: 1,
      departmentId: 1,
      isActive: true,
      lastLogin: null,
      createdDate: "2024-01-01",
    },
    {
      id: 3,
      username: "dean_dtvt",
      password: "dean123",
      roleId: 2,
      teacherId: 6,
      departmentId: 2,
      isActive: true,
      lastLogin: null,
      createdDate: "2024-01-01",
    },
    {
      id: 4,
      username: "dean_ck",
      password: "dean123",
      roleId: 2,
      teacherId: 11,
      departmentId: 3,
      isActive: true,
      lastLogin: null,
      createdDate: "2024-01-01",
    },
    {
      id: 5,
      username: "dean_kt",
      password: "dean123",
      roleId: 2,
      teacherId: 16,
      departmentId: 4,
      isActive: true,
      lastLogin: null,
      createdDate: "2024-01-01",
    },
    {
      id: 6,
      username: "dean_nn",
      password: "dean123",
      roleId: 2,
      teacherId: 21,
      departmentId: 5,
      isActive: true,
      lastLogin: null,
      createdDate: "2024-01-01",
    },
    // Giáo viên mẫu
    {
      id: 7,
      username: "gv001",
      password: "teacher123",
      roleId: 4,
      teacherId: 1,
      departmentId: 1,
      isActive: true,
      lastLogin: null,
      createdDate: "2024-01-01",
    },
    {
      id: 8,
      username: "gv002",
      password: "teacher123",
      roleId: 4,
      teacherId: 2,
      departmentId: 1,
      isActive: true,
      lastLogin: null,
      createdDate: "2024-01-01",
    },
    {
      id: 9,
      username: "gv006",
      password: "teacher123",
      roleId: 4,
      teacherId: 6,
      departmentId: 2,
      isActive: true,
      lastLogin: null,
      createdDate: "2024-01-01",
    },
  ],

  degrees: [
    {
      id: 1,
      fullName: "Tiến sĩ",
      shortName: "TS",
      coefficient: 1.7, // Thay đổi từ 2.0 thành 1.7
    },
    {
      id: 2,
      fullName: "Thạc sĩ",
      shortName: "ThS",
      coefficient: 1.5, // Thay đổi từ 1.5 giữ nguyên
    },
    {
      id: 3,
      fullName: "Đại học",
      shortName: "ĐH",
      coefficient: 1.3, // Thay đổi từ 1.0 thành 1.3
    },
    // Thêm bằng cấp mới
    {
      id: 4,
      fullName: "Phó Giáo sư",
      shortName: "PGS",
      coefficient: 2.0,
    },
    {
      id: 5,
      fullName: "Giáo sư",
      shortName: "GS",
      coefficient: 2.5,
    },
  ],

  departments: [
    {
      id: 1,
      fullName: "Khoa Công nghệ thông tin",
      shortName: "CNTT",
      description: "Đào tạo các chuyên ngành về công nghệ thông tin",
      deanId: 1,
      viceDeanIds: [2],
      establishedDate: "2010-01-01",
    },
    {
      id: 2,
      fullName: "Khoa Điện tử - Viễn thông",
      shortName: "ĐTVT",
      description: "Đào tạo các chuyên ngành về điện tử và viễn thông",
      deanId: 6,
      viceDeanIds: [7],
      establishedDate: "2008-01-01",
    },
    {
      id: 3,
      fullName: "Khoa Cơ khí",
      shortName: "CK",
      description: "Đào tạo các chuyên ngành về cơ khí và chế tạo máy",
      deanId: 11,
      viceDeanIds: [12],
      establishedDate: "2005-01-01",
    },
    {
      id: 4,
      fullName: "Khoa Kinh tế",
      shortName: "KT",
      description: "Đào tạo các chuyên ngành về kinh tế và quản trị kinh doanh",
      deanId: 16,
      viceDeanIds: [17],
      establishedDate: "2012-01-01",
    },
    {
      id: 5,
      fullName: "Khoa Ngoại ngữ",
      shortName: "NN",
      description: "Đào tạo các chuyên ngành về ngoại ngữ và văn hóa",
      deanId: 21,
      viceDeanIds: [22],
      establishedDate: "2015-01-01",
    },
    {
      id: 6,
      fullName: "Khoa Toán - Tin",
      shortName: "TT",
      description: "Đào tạo các chuyên ngành về toán học và tin học",
      deanId: null,
      viceDeanIds: [],
      establishedDate: "2007-01-01",
    },
  ],

  teachers: [
    // Khoa CNTT (15 giáo viên)
    {
      id: 1,
      code: "GV001",
      fullName: "Nguyễn Văn An",
      birthDate: "1980-05-15",
      phone: "0901234567",
      email: "nvan@university.edu.vn",
      departmentId: 1,
      degreeId: 1,
      coefficient: 1.3,
      position: "dean",
      isActive: true,
      hireDate: "2010-08-15",
      specialization: "Trí tuệ nhân tạo, Học máy",
    },
    {
      id: 2,
      code: "GV002",
      fullName: "Trần Thị Bình",
      birthDate: "1985-08-20",
      phone: "0912345678",
      email: "ttbinh@university.edu.vn",
      departmentId: 1,
      degreeId: 2,
      coefficient: 1.1,
      position: "vice_dean",
      isActive: true,
      hireDate: "2015-09-01",
      specialization: "Phát triển phần mềm, Cơ sở dữ liệu",
    },
    {
      id: 3,
      code: "GV003",
      fullName: "Phạm Văn Đức",
      birthDate: "1987-12-05",
      phone: "0934567890",
      email: "pvduc@university.edu.vn",
      departmentId: 1,
      degreeId: 2,
      coefficient: 1.0,
      position: "senior_lecturer",
      isActive: true,
      hireDate: "2018-02-01",
      specialization: "An toàn thông tin, Mạng máy tính",
    },
    {
      id: 4,
      code: "GV004",
      fullName: "Lê Thị Hoa",
      birthDate: "1990-03-12",
      phone: "0945678901",
      email: "lthoa@university.edu.vn",
      departmentId: 1,
      degreeId: 2,
      coefficient: 1.0,
      position: "lecturer",
      isActive: true,
      hireDate: "2020-09-01",
      specialization: "Lập trình web, JavaScript",
    },
    {
      id: 5,
      code: "GV005",
      fullName: "Võ Minh Tuấn",
      birthDate: "1988-11-30",
      phone: "0956789012",
      email: "vmtuan@university.edu.vn",
      departmentId: 1,
      degreeId: 1,
      coefficient: 1.2,
      position: "senior_lecturer",
      isActive: true,
      hireDate: "2016-01-15",
      specialization: "Khoa học dữ liệu, Big Data",
    },

    // Khoa ĐTVT (10 giáo viên)
    {
      id: 6,
      code: "GV006",
      fullName: "Lê Minh Cường",
      birthDate: "1982-03-10",
      phone: "0923456789",
      email: "lmcuong@university.edu.vn",
      departmentId: 2,
      degreeId: 1,
      coefficient: 1.3,
      position: "dean",
      isActive: true,
      hireDate: "2008-07-20",
      specialization: "Xử lý tín hiệu, Viễn thông",
    },
    {
      id: 7,
      code: "GV007",
      fullName: "Hoàng Thị Lan",
      birthDate: "1983-07-18",
      phone: "0945678901",
      email: "htlan@university.edu.vn",
      departmentId: 2,
      degreeId: 2,
      coefficient: 1.2,
      position: "vice_dean",
      isActive: true,
      hireDate: "2012-08-15",
      specialization: "Điện tử số, Vi xử lý",
    },
    {
      id: 8,
      code: "GV008",
      fullName: "Nguyễn Thanh Tùng",
      birthDate: "1986-09-25",
      phone: "0967890123",
      email: "nttung@university.edu.vn",
      departmentId: 2,
      degreeId: 2,
      coefficient: 1.1,
      position: "senior_lecturer",
      isActive: true,
      hireDate: "2017-03-01",
      specialization: "Mạng không dây, IoT",
    },
    {
      id: 9,
      code: "GV009",
      fullName: "Đặng Thị Mai",
      birthDate: "1991-01-14",
      phone: "0978901234",
      email: "dtmai@university.edu.vn",
      departmentId: 2,
      degreeId: 3,
      coefficient: 1.0,
      position: "lecturer",
      isActive: true,
      hireDate: "2021-08-01",
      specialization: "Kỹ thuật điều khiển, Tự động hóa",
    },
    {
      id: 10,
      code: "GV010",
      fullName: "Bùi Văn Nam",
      birthDate: "1985-06-08",
      phone: "0989012345",
      email: "bvnam@university.edu.vn",
      departmentId: 2,
      degreeId: 2,
      coefficient: 1.1,
      position: "lecturer",
      isActive: true,
      hireDate: "2019-02-15",
      specialization: "Hệ thống nhúng, FPGA",
    },

    // Khoa Cơ khí (12 giáo viên)
    {
      id: 11,
      code: "GV011",
      fullName: "Trần Văn Mạnh",
      birthDate: "1979-12-22",
      phone: "0990123456",
      email: "tvmanh@university.edu.vn",
      departmentId: 3,
      degreeId: 1,
      coefficient: 1.4,
      position: "dean",
      isActive: true,
      hireDate: "2005-09-01",
      specialization: "Thiết kế máy, CAD/CAM",
    },
    {
      id: 12,
      code: "GV012",
      fullName: "Lý Thị Nga",
      birthDate: "1984-04-17",
      phone: "0901234568",
      email: "ltnga@university.edu.vn",
      departmentId: 3,
      degreeId: 2,
      coefficient: 1.2,
      position: "vice_dean",
      isActive: true,
      hireDate: "2013-01-10",
      specialization: "Vật liệu học, Cơ học vật rắn",
    },
    {
      id: 13,
      code: "GV013",
      fullName: "Phạm Quốc Việt",
      birthDate: "1987-08-03",
      phone: "0912345679",
      email: "pqviet@university.edu.vn",
      departmentId: 3,
      degreeId: 2,
      coefficient: 1.1,
      position: "senior_lecturer",
      isActive: true,
      hireDate: "2018-06-15",
      specialization: "Nhiệt động lực học, Máy móc công nghiệp",
    },
    {
      id: 14,
      code: "GV014",
      fullName: "Ngô Thị Hương",
      birthDate: "1989-11-09",
      phone: "0923456780",
      email: "nthuong@university.edu.vn",
      departmentId: 3,
      degreeId: 3,
      coefficient: 1.0,
      position: "lecturer",
      isActive: true,
      hireDate: "2020-03-01",
      specialization: "Gia công cơ khí, CNC",
    },
    {
      id: 15,
      code: "GV015",
      fullName: "Vũ Văn Đạt",
      birthDate: "1986-02-26",
      phone: "0934567891",
      email: "vvdat@university.edu.vn",
      departmentId: 3,
      degreeId: 2,
      coefficient: 1.1,
      position: "lecturer",
      isActive: true,
      hireDate: "2017-09-15",
      specialization: "Robot công nghiệp, Tự động hóa",
    },

    // Khoa Kinh tế (10 giáo viên)
    {
      id: 16,
      code: "GV016",
      fullName: "Đỗ Thị Thanh",
      birthDate: "1981-07-11",
      phone: "0945678902",
      email: "dtthanh@university.edu.vn",
      departmentId: 4,
      degreeId: 1,
      coefficient: 1.3,
      position: "dean",
      isActive: true,
      hireDate: "2012-08-01",
      specialization: "Kinh tế vĩ mô, Chính sách tài chính",
    },
    {
      id: 17,
      code: "GV017",
      fullName: "Cao Văn Hùng",
      birthDate: "1983-10-05",
      phone: "0956789013",
      email: "cvhung@university.edu.vn",
      departmentId: 4,
      degreeId: 2,
      coefficient: 1.2,
      position: "vice_dean",
      isActive: true,
      hireDate: "2015-02-15",
      specialization: "Quản trị doanh nghiệp, Marketing",
    },
    {
      id: 18,
      code: "GV018",
      fullName: "Lương Thị Oanh",
      birthDate: "1988-01-19",
      phone: "0967890124",
      email: "ltoanh@university.edu.vn",
      departmentId: 4,
      degreeId: 2,
      coefficient: 1.1,
      position: "senior_lecturer",
      isActive: true,
      hireDate: "2019-09-01",
      specialization: "Kế toán, Tài chính doanh nghiệp",
    },
    {
      id: 19,
      code: "GV019",
      fullName: "Huỳnh Văn Phúc",
      birthDate: "1990-05-23",
      phone: "0978901235",
      email: "hvphuc@university.edu.vn",
      departmentId: 4,
      degreeId: 3,
      coefficient: 1.0,
      position: "lecturer",
      isActive: true,
      hireDate: "2021-01-15",
      specialization: "Thương mại điện tử, Logistics",
    },
    {
      id: 20,
      code: "GV020",
      fullName: "Tôn Thị Bích",
      birthDate: "1987-09-16",
      phone: "0989012346",
      email: "ttbich@university.edu.vn",
      departmentId: 4,
      degreeId: 2,
      coefficient: 1.1,
      position: "lecturer",
      isActive: true,
      hireDate: "2018-03-01",
      specialization: "Ngân hàng, Bảo hiểm",
    },

    // Khoa Ngoại ngữ (8 giáo viên)
    {
      id: 21,
      code: "GV021",
      fullName: "Smith John",
      birthDate: "1978-04-30",
      phone: "0990123457",
      email: "sjohn@university.edu.vn",
      departmentId: 5,
      degreeId: 2,
      coefficient: 1.3,
      position: "dean",
      isActive: true,
      hireDate: "2015-09-01",
      specialization: "Ngôn ngữ học Anh, Phương pháp giảng dạy",
    },
    {
      id: 22,
      code: "GV022",
      fullName: "Nguyễn Thị Linh",
      birthDate: "1986-08-12",
      phone: "0901234569",
      email: "ntlinh@university.edu.vn",
      departmentId: 5,
      degreeId: 2,
      coefficient: 1.2,
      position: "vice_dean",
      isActive: true,
      hireDate: "2017-02-01",
      specialization: "Tiếng Anh thương mại, TOEIC",
    },
    {
      id: 23,
      code: "GV023",
      fullName: "Wang Li",
      birthDate: "1985-12-07",
      phone: "0912345680",
      email: "wangli@university.edu.vn",
      departmentId: 5,
      degreeId: 2,
      coefficient: 1.1,
      position: "senior_lecturer",
      isActive: true,
      hireDate: "2018-08-15",
      specialization: "Tiếng Trung giao tiếp, HSK",
    },
    {
      id: 24,
      code: "GV024",
      fullName: "Tanaka Hiroshi",
      birthDate: "1982-06-18",
      phone: "0923456781",
      email: "thanaka@university.edu.vn",
      departmentId: 5,
      degreeId: 2,
      coefficient: 1.1,
      position: "lecturer",
      isActive: true,
      hireDate: "2019-01-15",
      specialization: "Tiếng Nhật cơ bản, JLPT",
    },
    {
      id: 25,
      code: "GV025",
      fullName: "Marie Dubois",
      birthDate: "1984-03-25",
      phone: "0934567892",
      email: "mdubois@university.edu.vn",
      departmentId: 5,
      degreeId: 2,
      coefficient: 1.1,
      position: "lecturer",
      isActive: true,
      hireDate: "2020-09-01",
      specialization: "Tiếng Pháp cơ bản, DELF",
    },

    // Khoa Toán-Tin (8 giáo viên)
    {
      id: 26,
      code: "GV026",
      fullName: "Nguyễn Công Minh",
      birthDate: "1980-10-14",
      phone: "0945678903",
      email: "ncminh@university.edu.vn",
      departmentId: 6,
      degreeId: 1,
      coefficient: 1.4,
      position: "senior_lecturer",
      isActive: true,
      hireDate: "2011-03-01",
      specialization: "Đại số tuyến tính, Toán rời rạc",
    },
    {
      id: 27,
      code: "GV027",
      fullName: "Phan Thị Thu",
      birthDate: "1987-05-28",
      phone: "0956789014",
      email: "ptthu@university.edu.vn",
      departmentId: 6,
      degreeId: 2,
      coefficient: 1.2,
      position: "senior_lecturer",
      isActive: true,
      hireDate: "2016-09-15",
      specialization: "Xác suất thống kê, Toán ứng dụng",
    },
    {
      id: 28,
      code: "GV028",
      fullName: "Lê Văn Quang",
      birthDate: "1985-11-03",
      phone: "0967890125",
      email: "lvquang@university.edu.vn",
      departmentId: 6,
      degreeId: 2,
      coefficient: 1.1,
      position: "lecturer",
      isActive: true,
      hireDate: "2018-01-15",
      specialization: "Giải tích, Phương trình vi phân",
    },
    // Thêm vào mảng teachers:

    {
      id: 29,
      code: "GV029",
      fullName: "PGS.TS Nguyễn Văn Minh",
      birthDate: "1975-03-15",
      phone: "0987654321",
      email: "nvminh@university.edu.vn",
      departmentId: 1,
      degreeId: 4, // Phó Giáo sư
      coefficient: 1.0,
      position: "senior_lecturer",
      isActive: true,
      hireDate: "2005-08-15",
      specialization: "Trí tuệ nhân tạo, Machine Learning",
    },
    {
      id: 30,
      code: "GV030",
      fullName: "GS.TS Trần Thị Lan Anh",
      birthDate: "1970-07-20",
      phone: "0976543210",
      email: "ttlananh@university.edu.vn",
      departmentId: 2,
      degreeId: 5, // Giáo sư
      coefficient: 1.0,
      position: "professor",
      isActive: true,
      hireDate: "2000-09-01",
      specialization: "Xử lý tín hiệu số, Viễn thông",
    },
  ],

  subjects: [
    // Khoa CNTT
    {
      id: 1,
      code: "IT101",
      name: "Lập trình cơ bản",
      credits: 3,
      coefficient: 1.0,
      periods: 45,
      departmentId: 1,
      isRequired: true,
      prerequisiteIds: [],
    },
    {
      id: 2,
      code: "IT201",
      name: "Cấu trúc dữ liệu và giải thuật",
      credits: 4,
      coefficient: 1.2,
      periods: 60,
      departmentId: 1,
      isRequired: true,
      prerequisiteIds: [1],
    },
    {
      id: 3,
      code: "IT301",
      name: "Công nghệ phần mềm",
      credits: 3,
      coefficient: 1.1,
      periods: 45,
      departmentId: 1,
      isRequired: true,
      prerequisiteIds: [1, 2],
    },
    {
      id: 4,
      code: "IT202",
      name: "Lập trình hướng đối tượng",
      credits: 3,
      coefficient: 1.1,
      periods: 45,
      departmentId: 1,
      isRequired: true,
      prerequisiteIds: [1],
    },
    {
      id: 5,
      code: "IT401",
      name: "Trí tuệ nhân tạo",
      credits: 3,
      coefficient: 1.3,
      periods: 45,
      departmentId: 1,
      isRequired: false,
      prerequisiteIds: [2],
    },
    {
      id: 6,
      code: "IT302",
      name: "Cơ sở dữ liệu",
      credits: 3,
      coefficient: 1.1,
      periods: 45,
      departmentId: 1,
      isRequired: true,
      prerequisiteIds: [2],
    },

    // Khoa ĐTVT
    {
      id: 7,
      code: "ET101",
      name: "Mạch điện tử cơ bản",
      credits: 3,
      coefficient: 1.1,
      periods: 45,
      departmentId: 2,
      isRequired: true,
      prerequisiteIds: [],
    },
    {
      id: 8,
      code: "ET201",
      name: "Xử lý tín hiệu số",
      credits: 4,
      coefficient: 1.3,
      periods: 60,
      departmentId: 2,
      isRequired: true,
      prerequisiteIds: [7],
    },
    {
      id: 9,
      code: "ET301",
      name: "Viễn thông",
      credits: 3,
      coefficient: 1.2,
      periods: 45,
      departmentId: 2,
      isRequired: true,
      prerequisiteIds: [7, 8],
    },
    {
      id: 10,
      code: "ET202",
      name: "Vi xử lý",
      credits: 3,
      coefficient: 1.2,
      periods: 45,
      departmentId: 2,
      isRequired: true,
      prerequisiteIds: [7],
    },

    // Khoa Cơ khí
    {
      id: 11,
      code: "ME101",
      fullName: "Vẽ kỹ thuật",
      credits: 2,
      coefficient: 1.0,
      periods: 30,
      departmentId: 3,
      isRequired: true,
      prerequisiteIds: [],
    },
    {
      id: 12,
      code: "ME201",
      fullName: "Cơ học kỹ thuật",
      credits: 4,
      coefficient: 1.2,
      periods: 60,
      departmentId: 3,
      isRequired: true,
      prerequisiteIds: [11],
    },
    {
      id: 13,
      code: "ME301",
      fullName: "Thiết kế máy",
      credits: 3,
      coefficient: 1.3,
      periods: 45,
      departmentId: 3,
      isRequired: true,
      prerequisiteIds: [11, 12],
    },
    {
      id: 14,
      code: "ME202",
      fullName: "Vật liệu học",
      credits: 3,
      coefficient: 1.1,
      periods: 45,
      departmentId: 3,
      isRequired: true,
      prerequisiteIds: [],
    },

    // Khoa Kinh tế
    {
      id: 15,
      code: "EC101",
      name: "Kinh tế học đại cương",
      credits: 3,
      coefficient: 1.0,
      periods: 45,
      departmentId: 4,
      isRequired: true,
      prerequisiteIds: [],
    },
    {
      id: 16,
      code: "EC201",
      name: "Quản trị học",
      credits: 3,
      coefficient: 1.1,
      periods: 45,
      departmentId: 4,
      isRequired: true,
      prerequisiteIds: [15],
    },
    {
      id: 17,
      code: "EC301",
      name: "Marketing",
      credits: 3,
      coefficient: 1.2,
      periods: 45,
      departmentId: 4,
      isRequired: true,
      prerequisiteIds: [15, 16],
    },
    {
      id: 18,
      code: "EC202",
      name: "Kế toán tài chính",
      credits: 3,
      coefficient: 1.1,
      periods: 45,
      departmentId: 4,
      isRequired: true,
      prerequisiteIds: [15],
    },

    // Khoa Ngoại ngữ
    {
      id: 19,
      code: "EN101",
      name: "Tiếng Anh cơ bản 1",
      credits: 3,
      coefficient: 1.0,
      periods: 45,
      departmentId: 5,
      isRequired: true,
      prerequisiteIds: [],
    },
    {
      id: 20,
      code: "EN201",
      name: "Tiếng Anh giao tiếp",
      credits: 3,
      coefficient: 1.1,
      periods: 45,
      departmentId: 5,
      isRequired: true,
      prerequisiteIds: [19],
    },
    {
      id: 21,
      code: "CH101",
      name: "Tiếng Trung cơ bản",
      credits: 3,
      coefficient: 1.0,
      periods: 45,
      departmentId: 5,
      isRequired: false,
      prerequisiteIds: [],
    },
    {
      id: 22,
      code: "JP101",
      name: "Tiếng Nhật cơ bản",
      credits: 3,
      coefficient: 1.0,
      periods: 45,
      departmentId: 5,
      isRequired: false,
      prerequisiteIds: [],
    },

    // Khoa Toán-Tin
    {
      id: 23,
      code: "MA101",
      name: "Toán cao cấp A1",
      credits: 3,
      coefficient: 1.0,
      periods: 45,
      departmentId: 6,
      isRequired: true,
      prerequisiteIds: [],
    },
    {
      id: 24,
      code: "MA201",
      name: "Đại số tuyến tính",
      credits: 3,
      coefficient: 1.1,
      periods: 45,
      departmentId: 6,
      isRequired: true,
      prerequisiteIds: [23],
    },
    {
      id: 25,
      code: "MA301",
      name: "Xác suất thống kê",
      credits: 3,
      coefficient: 1.2,
      periods: 45,
      departmentId: 6,
      isRequired: true,
      prerequisiteIds: [23, 24],
    },
  ],

  semesters: [
    {
      id: 1,
      name: "Học kỳ 1",
      academicYear: "2024-2025",
      startDate: "2024-09-01",
      endDate: "2024-12-31",
      isActive: true,
      registrationDeadline: "2024-08-15",
    },
    {
      id: 2,
      name: "Học kỳ 2",
      academicYear: "2024-2025",
      startDate: "2025-01-15",
      endDate: "2025-05-31",
      isActive: false,
      registrationDeadline: "2024-12-31",
    },
    {
      id: 3,
      name: "Học kỳ hè",
      academicYear: "2024-2025",
      startDate: "2025-06-15",
      endDate: "2025-08-31",
      isActive: false,
      registrationDeadline: "2025-05-31",
    },
  ],

  classes: [
    // Khoa CNTT - Học kỳ 1
    {
      id: 1,
      semesterId: 1,
      subjectId: 1,
      classCode: "IT101_01",
      className: "Lập trình cơ bản - Lớp 1",
      studentCount: 45,
      coefficient: 1.0,
      schedule: "Thứ 2, 4, 6 (7:00-9:30)",
      room: "A101",
      maxStudents: 50,
    },
    {
      id: 2,
      semesterId: 1,
      subjectId: 1,
      classCode: "IT101_02",
      className: "Lập trình cơ bản - Lớp 2",
      studentCount: 50,
      coefficient: 1.1,
      schedule: "Thứ 3, 5, 7 (7:00-9:30)",
      room: "A102",
      maxStudents: 50,
    },
    {
      id: 3,
      semesterId: 1,
      subjectId: 2,
      classCode: "IT201_01",
      className: "CTDL&GT - Lớp 1",
      studentCount: 40,
      coefficient: 1.0,
      schedule: "Thứ 2, 4, 6 (9:45-12:15)",
      room: "B201",
      maxStudents: 45,
    },
    {
      id: 4,
      semesterId: 1,
      subjectId: 3,
      classCode: "IT301_01",
      className: "Công nghệ phần mềm - Lớp 1",
      studentCount: 35,
      coefficient: 1.0,
      schedule: "Thứ 3, 5 (13:00-16:30)",
      room: "B202",
      maxStudents: 40,
    },
    {
      id: 5,
      semesterId: 1,
      subjectId: 4,
      classCode: "IT202_01",
      className: "Lập trình OOP - Lớp 1",
      studentCount: 42,
      coefficient: 1.0,
      schedule: "Thứ 2, 4 (13:00-16:30)",
      room: "A103",
      maxStudents: 45,
    },
    {
      id: 6,
      semesterId: 1,
      subjectId: 6,
      classCode: "IT302_01",
      className: "Cơ sở dữ liệu - Lớp 1",
      studentCount: 38,
      coefficient: 1.0,
      schedule: "Thứ 3, 5, 7 (9:45-12:15)",
      room: "B203",
      maxStudents: 40,
    },

    // Khoa ĐTVT - Học kỳ 1
    {
      id: 7,
      semesterId: 1,
      subjectId: 7,
      classCode: "ET101_01",
      className: "Mạch điện tử cơ bản - Lớp 1",
      studentCount: 35,
      coefficient: 1.0,
      schedule: "Thứ 3, 5 (13:00-16:30)",
      room: "C301",
      maxStudents: 40,
    },
    {
      id: 8,
      semesterId: 1,
      subjectId: 8,
      classCode: "ET201_01",
      className: "Xử lý tín hiệu số - Lớp 1",
      studentCount: 25,
      coefficient: 1.0,
      schedule: "Thứ 2, 4 (13:00-16:30)",
      room: "C302",
      maxStudents: 30,
    },
    {
      id: 9,
      semesterId: 1,
      subjectId: 9,
      classCode: "ET301_01",
      className: "Viễn thông - Lớp 1",
      studentCount: 30,
      coefficient: 1.0,
      schedule: "Thứ 6, 7 (7:00-10:30)",
      room: "C303",
      maxStudents: 35,
    },
    {
      id: 10,
      semesterId: 1,
      subjectId: 10,
      classCode: "ET202_01",
      className: "Vi xử lý - Lớp 1",
      studentCount: 28,
      coefficient: 1.0,
      schedule: "Thứ 2, 4, 6 (7:00-9:30)",
      room: "C304",
      maxStudents: 30,
    },

    // Khoa Cơ khí - Học kỳ 1
    {
      id: 11,
      semesterId: 1,
      subjectId: 11,
      classCode: "ME101_01",
      className: "Vẽ kỹ thuật - Lớp 1",
      studentCount: 40,
      coefficient: 1.0,
      schedule: "Thứ 2, 4 (7:00-10:30)",
      room: "D401",
      maxStudents: 45,
    },
    {
      id: 12,
      semesterId: 1,
      subjectId: 12,
      classCode: "ME201_01",
      className: "Cơ học kỹ thuật - Lớp 1",
      studentCount: 35,
      coefficient: 1.0,
      schedule: "Thứ 3, 5, 7 (7:00-9:30)",
      room: "D402",
      maxStudents: 40,
    },
    {
      id: 13,
      semesterId: 1,
      subjectId: 13,
      classCode: "ME301_01",
      className: "Thiết kế máy - Lớp 1",
      studentCount: 25,
      coefficient: 1.0,
      schedule: "Thứ 6, 7 (13:00-16:30)",
      room: "D403",
      maxStudents: 30,
    },
    {
      id: 14,
      semesterId: 1,
      subjectId: 14,
      classCode: "ME202_01",
      className: "Vật liệu học - Lớp 1",
      studentCount: 32,
      coefficient: 1.0,
      schedule: "Thứ 2, 4, 6 (13:00-15:30)",
      room: "D404",
      maxStudents: 35,
    },

    // Khoa Kinh tế - Học kỳ 1
    {
      id: 15,
      semesterId: 1,
      subjectId: 15,
      classCode: "EC101_01",
      className: "Kinh tế học đại cương - Lớp 1",
      studentCount: 50,
      coefficient: 1.1,
      schedule: "Thứ 2, 4, 6 (7:00-9:30)",
      room: "E501",
      maxStudents: 60,
    },
    {
      id: 16,
      semesterId: 1,
      subjectId: 16,
      classCode: "EC201_01",
      className: "Quản trị học - Lớp 1",
      studentCount: 45,
      coefficient: 1.0,
      schedule: "Thứ 3, 5, 7 (9:45-12:15)",
      room: "E502",
      maxStudents: 50,
    },
    {
      id: 17,
      semesterId: 1,
      subjectId: 17,
      classCode: "EC301_01",
      className: "Marketing - Lớp 1",
      studentCount: 38,
      coefficient: 1.0,
      schedule: "Thứ 2, 4 (13:00-16:30)",
      room: "E503",
      maxStudents: 40,
    },
    {
      id: 18,
      semesterId: 1,
      subjectId: 18,
      classCode: "EC202_01",
      className: "Kế toán tài chính - Lớp 1",
      studentCount: 42,
      coefficient: 1.0,
      schedule: "Thứ 3, 5 (13:00-16:30)",
      room: "E504",
      maxStudents: 45,
    },

    // Khoa Ngoại ngữ - Học kỳ 1
    {
      id: 19,
      semesterId: 1,
      subjectId: 19,
      classCode: "EN101_01",
      className: "Tiếng Anh cơ bản 1 - Lớp 1",
      studentCount: 30,
      coefficient: 1.0,
      schedule: "Thứ 2, 4, 6 (7:00-9:30)",
      room: "F601",
      maxStudents: 35,
    },
    {
      id: 20,
      semesterId: 1,
      subjectId: 20,
      classCode: "EN201_01",
      className: "Tiếng Anh giao tiếp - Lớp 1",
      studentCount: 25,
      coefficient: 1.0,
      schedule: "Thứ 3, 5, 7 (7:00-9:30)",
      room: "F602",
      maxStudents: 30,
    },
    {
      id: 21,
      semesterId: 1,
      subjectId: 21,
      classCode: "CH101_01",
      className: "Tiếng Trung cơ bản - Lớp 1",
      studentCount: 20,
      coefficient: 1.0,
      schedule: "Thứ 2, 4 (13:00-16:30)",
      room: "F603",
      maxStudents: 25,
    },
    {
      id: 22,
      semesterId: 1,
      subjectId: 22,
      classCode: "JP101_01",
      className: "Tiếng Nhật cơ bản - Lớp 1",
      studentCount: 18,
      coefficient: 1.0,
      schedule: "Thứ 3, 5 (13:00-16:30)",
      room: "F604",
      maxStudents: 25,
    },

    // Khoa Toán-Tin - Học kỳ 1
    {
      id: 23,
      semesterId: 1,
      subjectId: 23,
      classCode: "MA101_01",
      className: "Toán cao cấp A1 - Lớp 1",
      studentCount: 60,
      coefficient: 1.2,
      schedule: "Thứ 2, 4, 6 (7:00-9:30)",
      room: "G701",
      maxStudents: 70,
    },
    {
      id: 24,
      semesterId: 1,
      subjectId: 24,
      classCode: "MA201_01",
      className: "Đại số tuyến tính - Lớp 1",
      studentCount: 48,
      coefficient: 1.0,
      schedule: "Thứ 3, 5, 7 (9:45-12:15)",
      room: "G702",
      maxStudents: 50,
    },
    {
      id: 25,
      semesterId: 1,
      subjectId: 25,
      classCode: "MA301_01",
      className: "Xác suất thống kê - Lớp 1",
      studentCount: 35,
      coefficient: 1.0,
      schedule: "Thứ 2, 4 (13:00-16:30)",
      room: "G703",
      maxStudents: 40,
    },
  ],

  assignments: [
    // Khoa CNTT
    {
      id: 1,
      teacherId: 1,
      classId: 1,
      assignedDate: "2024-08-15",
      assignedBy: 2,
      status: "active",
      notes: "Trưởng khoa trực tiếp giảng dạy",
    },
    {
      id: 2,
      teacherId: 2,
      classId: 2,
      assignedDate: "2024-08-16",
      assignedBy: 2,
      status: "active",
      notes: "",
    },
    {
      id: 3,
      teacherId: 3,
      classId: 3,
      assignedDate: "2024-08-17",
      assignedBy: 2,
      status: "active",
      notes: "",
    },
    {
      id: 4,
      teacherId: 4,
      classId: 4,
      assignedDate: "2024-08-18",
      assignedBy: 2,
      status: "active",
      notes: "",
    },
    {
      id: 5,
      teacherId: 5,
      classId: 5,
      assignedDate: "2024-08-19",
      assignedBy: 2,
      status: "active",
      notes: "",
    },
    {
      id: 6,
      teacherId: 1,
      classId: 6,
      assignedDate: "2024-08-20",
      assignedBy: 2,
      status: "active",
      notes: "Phân công thêm",
    },

    // Khoa ĐTVT
    {
      id: 7,
      teacherId: 6,
      classId: 7,
      assignedDate: "2024-08-18",
      assignedBy: 3,
      status: "active",
      notes: "Trưởng khoa ĐTVT",
    },
    {
      id: 8,
      teacherId: 7,
      classId: 8,
      assignedDate: "2024-08-19",
      assignedBy: 3,
      status: "active",
      notes: "",
    },
    {
      id: 9,
      teacherId: 8,
      classId: 9,
      assignedDate: "2024-08-20",
      assignedBy: 3,
      status: "active",
      notes: "",
    },
    {
      id: 10,
      teacherId: 9,
      classId: 10,
      assignedDate: "2024-08-21",
      assignedBy: 3,
      status: "active",
      notes: "",
    },

    // Khoa Cơ khí
    {
      id: 11,
      teacherId: 11,
      classId: 11,
      assignedDate: "2024-08-22",
      assignedBy: 4,
      status: "active",
      notes: "Trưởng khoa Cơ khí",
    },
    {
      id: 12,
      teacherId: 12,
      classId: 12,
      assignedDate: "2024-08-23",
      assignedBy: 4,
      status: "active",
      notes: "",
    },
    {
      id: 13,
      teacherId: 13,
      classId: 13,
      assignedDate: "2024-08-24",
      assignedBy: 4,
      status: "active",
      notes: "",
    },
    {
      id: 14,
      teacherId: 14,
      classId: 14,
      assignedDate: "2024-08-25",
      assignedBy: 4,
      status: "active",
      notes: "",
    },

    // Khoa Kinh tế
    {
      id: 15,
      teacherId: 16,
      classId: 15,
      assignedDate: "2024-08-26",
      assignedBy: 5,
      status: "active",
      notes: "Trưởng khoa Kinh tế",
    },
    {
      id: 16,
      teacherId: 17,
      classId: 16,
      assignedDate: "2024-08-27",
      assignedBy: 5,
      status: "active",
      notes: "",
    },
    {
      id: 17,
      teacherId: 18,
      classId: 17,
      assignedDate: "2024-08-28",
      assignedBy: 5,
      status: "active",
      notes: "",
    },
    {
      id: 18,
      teacherId: 19,
      classId: 18,
      assignedDate: "2024-08-29",
      assignedBy: 5,
      status: "active",
      notes: "",
    },

    // Khoa Ngoại ngữ
    {
      id: 19,
      teacherId: 21,
      classId: 19,
      assignedDate: "2024-08-30",
      assignedBy: 6,
      status: "active",
      notes: "Trưởng khoa Ngoại ngữ",
    },
    {
      id: 20,
      teacherId: 22,
      classId: 20,
      assignedDate: "2024-08-31",
      assignedBy: 6,
      status: "active",
      notes: "",
    },
    {
      id: 21,
      teacherId: 23,
      classId: 21,
      assignedDate: "2024-09-01",
      assignedBy: 6,
      status: "active",
      notes: "",
    },
    {
      id: 22,
      teacherId: 24,
      classId: 22,
      assignedDate: "2024-09-02",
      assignedBy: 6,
      status: "active",
      notes: "",
    },

    // Khoa Toán-Tin
    {
      id: 23,
      teacherId: 26,
      classId: 23,
      assignedDate: "2024-09-03",
      assignedBy: 1,
      status: "active",
      notes: "Phân công bởi Admin",
    },
    {
      id: 24,
      teacherId: 27,
      classId: 24,
      assignedDate: "2024-09-04",
      assignedBy: 1,
      status: "active",
      notes: "",
    },
    {
      id: 25,
      teacherId: 28,
      classId: 25,
      assignedDate: "2024-09-05",
      assignedBy: 1,
      status: "active",
      notes: "",
    },

    // Phân công bổ sung cho một số giáo viên
    {
      id: 26,
      teacherId: 10,
      classId: 8,
      assignedDate: "2024-09-06",
      assignedBy: 3,
      status: "active",
      notes: "Phân công thêm lớp",
    },
    {
      id: 27,
      teacherId: 15,
      classId: 12,
      assignedDate: "2024-09-07",
      assignedBy: 4,
      status: "active",
      notes: "Hỗ trợ giảng dạy",
    },
    {
      id: 28,
      teacherId: 20,
      classId: 16,
      assignedDate: "2024-09-08",
      assignedBy: 5,
      status: "active",
      notes: "Phân công bổ sung",
    },
  ],

  paymentSettings: {
    baseRatePerPeriod: 150000, // Thay đổi từ 50000 thành 150000
    baseAllowance: 200000,
    socialInsuranceRate: 8.0,
    incomeTaxRate: 10.0,
    overtimeRate: 1.5,
    holidayRate: 2.0,
    minSalary: 1000000,
    maxClassesPerSemester: 8,
    lastUpdated: "2024-01-01",
    updatedBy: 1,
  },

  classCoefficients: [
    {
      id: 1,
      studentRange: "<20",
      coefficient: -0.3,
      description: "Lớp rất nhỏ",
      color: "#ef4444",
    },
    {
      id: 2,
      studentRange: "20-29",
      coefficient: -0.2,
      description: "Lớp nhỏ",
      color: "#f59e0b",
    },
    {
      id: 3,
      studentRange: "30-39",
      coefficient: -0.1,
      description: "Lớp trung bình nhỏ",
      color: "#eab308",
    },
    {
      id: 4,
      studentRange: "40-49",
      coefficient: 0.0,
      description: "Lớp chuẩn",
      color: "#10b981",
    },
    {
      id: 5,
      studentRange: "50-59",
      coefficient: 0.1,
      description: "Lớp lớn",
      color: "#3b82f6",
    },
    {
      id: 6,
      studentRange: "60-69",
      coefficient: 0.2,
      description: "Lớp rất lớn",
      color: "#8b5cf6",
    },
    {
      id: 7,
      studentRange: "70-79",
      coefficient: 0.3,
      description: "Lớp cực lớn",
      color: "#dc2626",
    },
    {
      id: 8,
      studentRange: "80+",
      coefficient: 0.4,
      description: "Lớp siêu lớn",
      color: "#7c2d12",
    },
  ],

  systemSettings: {
    schoolName: "Trường Đại học ABC",
    schoolAddress: "123 Đường ABC, TP.HCM",
    schoolPhone: "(028) 12345678",
    schoolEmail: "info@university.edu.vn",
    currentAcademicYear: "2024-2025",
    currentSemesterId: 1,
    autoBackup: true,
    backupFrequency: "daily",
    lastBackup: null,
    version: "1.0.0",
  },

  auditLogs: [
    {
      id: 1,
      userId: 1,
      action: "SYSTEM_INIT",
      targetType: "system",
      targetId: null,
      changes: { message: "Khởi tạo hệ thống với dữ liệu mẫu mở rộng" },
      timestamp: "2024-01-01T10:00:00Z",
      ipAddress: "192.168.1.1",
    },
  ],
};

// Utility functions for data management
const DataManager = {
  getNextId: (collection) => {
    return Math.max(...collection.map((item) => item.id), 0) + 1;
  },

  generateCode: (prefix, collection) => {
    const maxNum = Math.max(
      ...collection
        .filter((item) => item.code && item.code.startsWith(prefix))
        .map((item) => parseInt(item.code.replace(prefix, "")) || 0),
      0
    );
    return `${prefix}${String(maxNum + 1).padStart(3, "0")}`;
  },

  saveToLocalStorage: () => {
    localStorage.setItem("teachPayData", JSON.stringify(sampleData));
  },

  loadFromLocalStorage: () => {
    const saved = localStorage.getItem("teachPayData");
    if (saved) {
      const loadedData = JSON.parse(saved);
      Object.assign(sampleData, loadedData);
    }
  },

  resetData: () => {
    localStorage.removeItem("teachPayData");
    location.reload();
  },

  getCurrentSemester: () => {
    return sampleData.semesters.find(
      (s) => s.id === sampleData.systemSettings.currentSemesterId
    );
  },

  getTeachersByDepartment: (departmentId) => {
    return sampleData.teachers.filter((t) => t.departmentId === departmentId);
  },

  getClassesByDepartment: (departmentId) => {
    const departmentSubjects = sampleData.subjects.filter(
      (s) => s.departmentId === departmentId
    );
    const subjectIds = departmentSubjects.map((s) => s.id);
    return sampleData.classes.filter((c) => subjectIds.includes(c.subjectId));
  },

  getAssignmentsByTeacher: (teacherId) => {
    return sampleData.assignments.filter((a) => a.teacherId === teacherId);
  },

  getUserByTeacherId: (teacherId) => {
    return sampleData.users.find((u) => u.teacherId === teacherId);
  },

  addAuditLog: (userId, action, targetType, targetId, changes) => {
    const log = {
      id: DataManager.getNextId(sampleData.auditLogs),
      userId,
      action,
      targetType,
      targetId,
      changes,
      timestamp: new Date().toISOString(),
      ipAddress: "127.0.0.1",
    };
    sampleData.auditLogs.push(log);
    DataManager.saveToLocalStorage();
  },

  // Thống kê nhanh
  getStatistics: () => {
    return {
      totalTeachers: sampleData.teachers.length,
      totalDepartments: sampleData.departments.length,
      totalSubjects: sampleData.subjects.length,
      totalClasses: sampleData.classes.length,
      totalAssignments: sampleData.assignments.length,
      assignmentRate: (
        (sampleData.assignments.length / sampleData.classes.length) *
        100
      ).toFixed(1),
      teachersWithAssignments: new Set(
        sampleData.assignments.map((a) => a.teacherId)
      ).size,
      unassignedClasses:
        sampleData.classes.length - sampleData.assignments.length,
    };
  },
};

// Load data when script loads
DataManager.loadFromLocalStorage();
